/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include "gpio.h"



#if !defined(_SOFT_FP) && defined(_ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	led_init();
	switch_init();
	int i=0;
	while(1){
		if(switch_on() && i==0){
			while(switch_on()){
				green_on();
				blue_off();
			}
			i++;
		}
		if(switch_on() && i==1){
			while(switch_on()){
				green_off();
				blue_on();
			}
			i++;
		}
		if(switch_on() && i==2){
			while(switch_on()){
				green_on();
				blue_on();
			}
			i=0;
		}
		else{
			green_off();
			blue_off();
		}
	}
}
