/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include"stm32f407xx.h"

#define BV(n) (1 << (n))

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void cycle(void);
void init(void);

int main(void){
	init();
	while(1){
		cycle();
	}
}

void init(void){
	RCC->AHB1ENR |= BV(3);

	GPIOD->MODER |= BV(24) | BV(26) | BV(28) | BV(30);
	GPIOD->MODER &= ~(BV(25) | BV(27) | BV(29) | BV(31));

	GPIOD->OTYPER &= ~(BV(12) | BV(13) | BV(14) | BV(15));

	GPIOD->OSPEEDR &= ~(BV(24) | BV(25) | BV(26) | BV(27) | BV(28) | BV(29) | BV(30) | BV(31));

	GPIOD->PUPDR &= ~(BV(24) | BV(25) | BV(26) | BV(27) | BV(28) | BV(29) | BV(30) | BV(31));
}

void cycle(void){
	GPIOD->ODR |= BV(15);
	GPIOD->ODR &= ~(BV(13) | BV(14) | BV(12));
	DelayMs(500);
	GPIOD->ODR |= BV(14);
	GPIOD->ODR &= ~(BV(12) | BV(13) | BV(15));
	DelayMs(500);
	GPIOD->ODR |= BV(13);
	GPIOD->ODR &= ~(BV(12) | BV(14) | BV(15));
	DelayMs(500);
	GPIOD->ODR |= BV(12);
	GPIOD->ODR &= ~(BV(15) | BV(14) | BV(13));
	DelayMs(500);
}




