/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include"stm32f407xx.h"

#define BV(n) (1 << (n))

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void init(void);
void on(void);
void off(void);

int main(void){
	init();
	while(1){
		on();
		DelayMs(1000);
		off();
		DelayMs(1000);
	}
}

void init(void){
	RCC->AHB1ENR |= BV(3);

	GPIOD->MODER |= BV(24);
	GPIOD->MODER &= ~BV(25);

	GPIOD->OTYPER &= ~BV(12);

	GPIOD->OSPEEDR &= ~(BV(24) | BV(25));

	GPIOD->PUPDR &= ~(BV(24) | BV(25));
}

void on(void){
	GPIOD->ODR |= BV(12);
}
void off(void){
	GPIOD->ODR &= ~BV(12);
}






