/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include "gpio.h"
#include "ext_trig.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//volatile forces the compiler to store the variable in main memory rather than storing in cache
//generally when running the code the compiler first stores the values in cache and then runs ,this can cause problems
//since it can happen that compiler stores value one time and uses the same value for other times too .to avoid that
//we use volatile to tell the compiler to directly access value from main memory .

int main(void)
{
	led_init();
	ext_trig();
}









